---

- name: Get hostname after 127.0.1.1
  command: awk '/^127\.0\.1\.1/ { print $2 }' /etc/hosts
  register: hostname_from_hosts

- name: Remove file puppet.conf
  file:
    path: /etc/puppetlabs/puppet/puppet.conf
    state: absent
  become: true

- name: tranfer template file
  template:
    src: templates/puppet.conf.j2
    dest: /etc/puppetlabs/puppet/puppet.conf
  become: true

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ puppet_agnet_ipv4 }} {{ puppet_agent_name }}'
    insertafter: '^ '
    state: present
  become: true

- name: Add puppetserver to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ puppet_server_ipv4 }} {{ puppet_server_name }}'
    insertafter: '^ '
    state: present
  become: true

- name: Enable puppet
  systemd_service:
    name: puppet
    enabled: true
    state: started
  become: true
