---

- name: Download Puppet 8 release package
  get_url:
    url: '{{ puppet_deb_url }}'
    dest: /tmp/

- name: install puppet repo file
  apt:
    deb: /tmp/{{ puppet_deb }}
  become: true

- name: apt-get update
  apt:
    update_cache: true
  become: true

- name: install puppet agent
  apt:
    name: puppet-agent
    state: present
  become: true

- name: Add puppet path to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/opt/puppetlabs/bin:$PATH'
    insertafter: EOF
    state: present

- name: Update .bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

